django/RealEstate360/urls.py
from django.urls import path
from . import views


app_name = "RealEstate360"
urlpatterns = [
    path("", views.loginfunc, name="login"),
    path("logout/", views.logoutfunc, name="logout"),
    path("propertyinfos_list/", views.propertyinfos_list, name="propertyinfos_list"),
    path("propertyinfo_create/", views.propertyinfo_create, name="propertyinfo_create"),
    path(
        "propertyinfo_edit/<int:basic_information_id>/",
        views.propertyinfo_edit,
        name="propertyinfo_edit",
    ),
    path(
        "propertyinfo_detail/<int:basic_information_id>/",
        views.propertyinfo_detail,
        name="propertyinfo_detail",
    ),
    path(
        "propertyinfo_inactive/<int:basic_information_id>/",
        views.propertyinfo_inactive,
        name="propertyinfo_inactive",
    ),
    path("get_properties/", views.get_properties, name="get_properties"),
]

django/estate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("RealEstate360.urls")),
]

django/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- GoogleFontsインポート/フォント名：BIZ UDPGothic -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BIZ+UDPGothic:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CDN読み込み -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- staticフォルダ内のcss読み込み -->
    {% load static %}
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/custom-color-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'js/link-underbar.js' %}"></script>
    {% block head %}{% endblock %}
    <!-- 各ページのタイトル読み込み -->
    {% block title %}{% endblock %}
</head>


<body>
    <!-- ヘッダー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">

            <div class="navbar-brand">
                <img src="{% static 'img/web-header-logo.svg' %}" alt="" width="85" height="48.1"
                    class="navbar-brand__img">
            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul id="nav-list" class="navbar-nav mx-auto">
                    <li class="nav-item ms-lg-5">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'RealEstate360:propertyinfos_list' %}">物件一覧</a>
                    </li>
                    <li class="nav-item ms-lg-5">
                        <a class="nav-link active" aria-current="page"
                            href="{% url 'RealEstate360:propertyinfo_create' %}">新規登録</a>
                    </li>
                </ul>

                <button type="button" class="logout-btn btn-secondary flex-shrink-0 ms-auto my-sm-2" data-bs-toggle="modal" data-bs-target="#logout-modal" data-backdrop="true">
                    ログアウト
                </button>
                <div class="modal fade" id="logout-modal" tabindex="-1" aria-labelledby="exampleModalLabel">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">ログアウト</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="閉じる"></button>
                            </div>
                            <div class="modal-body">
                                <p>ログアウトしますか？</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn logout-button btn-cancel" data-bs-dismiss="modal">キャンセル</button>
                                <button type="button" class="btn btn-primary logout-button">
                                    <a class="text-white" href="{% url 'RealEstate360:logout' %}">OK</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>


    <!-- 各ページのbodyタグ内読み込み -->
    {% block content %}{% endblock %}


    <!-- Bootstrap JavaScript読み込み -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>


    {% block scripts %}
        <script src="{% static 'js/link-underbar.js' %}"></script>
    {% endblock %}
</body>

</html>

django/templates/create_propertyinfo.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block header_links %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'RealEstate360:view_propertyinfos' %}">View</a>
{% endblock %}

{% block content %}
<h1>物件情報の登録</h1>
<form method="post">
  {% csrf_token %}
  {{ basic_information_form.as_p }}
  {{ city_planning_form.as_p }}
  {{ building_information_form.as_p }}
  {{ land_information_form.as_p }}
  {{ infrastructure_information_form.as_p }}
  <button type="submit">登録</button>
</form>
{% endblock %}

django/templates/list.html
{% extends 'base.html' %}

{% block head %}
<!-- CSS読み込みの記述 -->
{% load static %}
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block title %}
<title>物件一覧</title>
{% endblock %}

{% block content %}

<!-- ページタイトル -->
<div class="page__title container-lg container-md container-sm">
    <div class="row page-name">
        <div class="col">
            <h2>物件情報一覧</h2>
        </div>
    </div>
    <div class="row">
        <div class="container col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 form--select__address">
            <div class="row gx-1 gx-sm-1 gx-md-1 gx-lg-0 gx-xl-0">
                <div id="search-text" class="col col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 text-center py-1 px-4 border-1">住所で検索</div>
                <div class="col col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 form--address">
                    <select id="geoapi-prefectures" name="geoapi-prefectures" class="form-select">
                        <option value="都道府県を選択してください">都道府県を選択してください</option>
                    </select>
                </div>
                <div class="col col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 form--address">
                    <select id="geoapi-cities" name="geoapi-cities" class="form-select">
                        <option value="市区町村名を選択してください">市区町村名を選択してください</option>
                    </select>
                </div>
                <div class="col col-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 form--address">
                    <select id="geoapi-towns" name="geoapi-towns" class="form-select">
                        <option value="町域を選択してください">町域を選択してください</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 一覧リストの項目名 -->
<div class="container-lg container-md container-sm mb-5">
    <div class="row list__title gx-sm-0 gx-md-1">
        <div class="col-4">
            <h3 class="list__title--property">物件名</h3>
        </div>
        <div class="col-4">
            <h3 class="list__title--tagname">管理番号</h3>
        </div>
        <div class="col-3">
            <h3 class="list__title--location">住所地</h3>
        </div>
        <div class="col-1"></div>
    </div>

    <!-- 物件リストの列 -->
    <div id="property-lists">
        {% for basic_information in basic_informations %}
        <div class="row list__item gx-1">
            <a href="{% url 'RealEstate360:propertyinfo_detail' basic_information.basic_information_id %}"
                class="d-flex">
                <div class="col-4">
                    <p class="list__item--property_name">{{ basic_information.property_name }}</p>
                </div>
                <div class="col-4">
                    <p>{{ basic_information.control_number }}</p>
                </div>
                <div class="col-3">
                    <p>{{ basic_information.address }}</p>
                </div>
                <div class="col-1 list__item--arrow">
                    <img src="{% static 'img/web-arrow.svg' %}" alt="詳細ページを見る" width="12.5" height="25"
                        class="web-arrow">
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="http://geoapi.heartrails.com/api/geoapi.js"></script>
<script>
    function fetchProperties() {
        var prefectureSelect = document.getElementById('geoapi-prefectures');
        var citySelect = document.getElementById('geoapi-cities');
        var townSelect = document.getElementById('geoapi-towns');
        var selectedPrefecture = (prefectureSelect.selectedIndex != 0) ? prefectureSelect.value : "";
        var selectedCity = (citySelect.selectedIndex != 0) ? citySelect.value : "";
        var selectedTown = (townSelect.selectedIndex != 0) ? townSelect.value : "";

        fetch('/get_properties/?prefecture=' + selectedPrefecture + '&city=' + selectedCity + '&town=' + selectedTown)
            .then(response => response.json())
            .then(data => {

                var propertyLists = document.getElementById('property-lists');
                propertyLists.innerHTML = '';  // 物件リストを一度空にする

                data.forEach(property => {
                    var listItem = `
                        <div class="row list__item gx-1">
                            <a href="/propertyinfo_detail/${property.basic_information_id}" class="d-flex">
                                <div class="col-4">
                                    <p class="list__item--tagname">${property.control_number}</p>
                                </div>
                                <div class="col-4">
                                    <p>${property.property_name}</p>
                                </div>
                                <div class="col-3">
                                    <p>${property.location}</p>
                                </div>
                                <div class="col-1 list__item--arrow">
                                    <img src="/static/img/web-arrow.svg" alt="詳細ページを見る" width="12.5" height="25" class="web-arrow">
                                </div>
                            </a>
                        </div>`;
                    // 生成したHTMLを物件リストに追加
                    propertyLists.innerHTML += listItem;
                })
            })
    }
    document.getElementById('geoapi-prefectures').addEventListener('change', fetchProperties);
    document.getElementById('geoapi-cities').addEventListener('change', fetchProperties);
    document.getElementById('geoapi-towns').addEventListener('change', fetchProperties);
</script>
{% endblock %}

django/templates/login.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- GoogleFontsインポート/フォント名：BIZ UDPGothic -->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=BIZ+UDPGothic:wght@400;700&display=swap"
            rel="stylesheet"
        />

        <!-- Bootstrap CDN読み込み -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
        />

        <!-- staticフォルダ内のcss読み込み -->
        {% load static %}
        <link rel="icon" href="{% static 'img/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/login.css' %}" />
        <link
            rel="stylesheet"
            href="{% static 'css/custom-color-bootstrap.css' %}"
        />
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />

        <title>REAL ESTATE 360</title>
    </head>
    {% block content %}
    <body>
        <div class="container vh-100">
            <div class="row vh-100">
                <div class="col-4 d-none d-lg-block"></div>
                <div class="col-12 col-lg-4 my-auto">
                    <img
                        src="{% static 'img/web-loginpage-logo.svg' %}"
                        alt=""
                        width="286"
                        height="162"
                        class="mx-auto d-block"
                    />
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3 mt-5">
                            <label for="username" class="form-label fw-bold"
                                >ユーザー名</label
                            >
                            <input
                                type="text"
                                class="form-control"
                                id="floatingInput"
                                name="username"
                            />
                        </div>
                        <div class="mb-5">
                            <label for="password" class="form-label fw-bold"
                                >パスワード</label
                            >
                            <input
                                type="password"
                                class="form-control"
                                id="floatingPassword"
                                name="password"
                            />
                        </div>
                        <button type="submit" class="w-100 rounded-pill p-2 btn-login">
                            ログイン
                        </button>
                    </form>
                </div>
                <div class="col-4 d-none d-lg-block"></div>
            </div>
        </div>
        <!-- Bootstrap JavaScript読み込み -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
        ></script>
    </body>
    {% endblock content %}
</html>

django/templates/propertyinfo_create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block header_links %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'RealEstate360:propertyinfos_list' %}">View</a>
{% endblock %}

{% block content %}
<h1>物件情報の登録</h1>
<form method="post">
  {% csrf_token %}
  {{ basic_information_form.as_p }}
  {{ city_planning_form.as_p }}
  {{ building_information_form.as_p }}
  {{ land_information_form.as_p }}
  {{ infrastructure_information_form.as_p }}
  <button type="submit">登録</button>
</form>
{% endblock %}

django/templates/propertyinfo_detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block header_links %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'RealEstate360:propertyinfos_list' %}">View</a>
<a href="{% url 'RealEstate360:propertyinfo_create' %}">Create</a>
{% endblock %}

{% block content %}
<h2>{{ basic_information.property_name }} の情報</h2>
<h3>基本情報</h3>
<table>
  {% for field, value in basic_information_fields %}
  <tr>
    <th>{{ field.verbose_name }}</th>
    <td>{{ value }}</td>
  </tr>
  {% endfor %}
</table>
<h3>都市計画情報</h3>
<table>
  {% for field, value in city_planning_fields %}
  <tr>
    <th>{{ field.verbose_name }}</th>
    <td>{{ value }}</td>
  </tr>
  {% endfor %}
</table>
<h3>建物情報</h3>
<table>
  {% for field, value in building_information_fields %}
  <tr>
    <th>{{ field.verbose_name }}</th>
    <td>{{ value }}</td>
  </tr>
  {% endfor %}
</table>
<h3>土地情報</h3>
<table>
  {% for field, value in land_information_fields %}
  <tr>
    <th>{{ field.verbose_name }}</th>
    <td>{{ value }}</td>
  </tr>
  {% endfor %}
</table>
<h3>インフラ情報</h3>
<table>
  {% for field, value in infrastructure_information_fields %}
  <tr>
    <th>{{ field.verbose_name }}</th>
    <td>{{ value }}</td>
  </tr>
  {% endfor %}
</table>
<a href="{% url 'RealEstate360:propertyinfo_edit' basic_information.basic_information_id %}">編集する</a>

<!-- 削除フォームの追加 -->
<form method="POST" action="{% url 'RealEstate360:propertyinfo_inactive' basic_information.basic_information_id %}">
  {% csrf_token %}
  <input type="hidden" name="is_active" value="false">
  <input type="submit" value="削除する" onclick="return confirm('本当に削除してもよろしいですか？')">
</form>

{% endblock %}

django/templates/propertyinfo_edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock %}

{% block header_links %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'RealEstate360:propertyinfos_list' %}">View</a>
{% endblock %}

{% block content %}
<h1>物件情報の更新</h1>
<form method="post">
  {% csrf_token %}
  {% for form in forms %}
  <table>
    {% for field in form %}
    <tr>
      <th>{{ field.label }}:</th>
      <td>{{ field }}</td>
    </tr>
    {% endfor %}
  </table>
  {% endfor %}
  <button type="submit">更新</button>
</form>
<a href="{% url 'RealEstate360:propertyinfo_detail' basic_information.basic_information_id %}">編集しない</a>
{% endblock %}

django/templates/propertyinfos_list.html
{% extends 'base.html' %}

{% block title %}物件一覧{% endblock %}

{% block header_links %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'RealEstate360:propertyinfo_create' %}">Create</a>
{% endblock %}

{% block content %}
<h2>物件情報一覧</h2>
<ul>
  {% for basic_information in basic_informations %}
  <li>
    <a href="{% url 'RealEstate360:propertyinfo_detail' basic_information.basic_information_id %}">
      {{ basic_information.property_name }}
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock %}